# Utiliser l'image Kali
FROM kalilinux/kali-rolling

# Installation des packages nécessaires
RUN apt-get update -y && \
apt-get install -y --no-install-recommends --no-install-suggests \
 rsyslog \
 curl \
 tcpdump \
 net-tools

